defaults:
        - run: local
        - data: maths
        - override hydra/hydra_logging: none
        - override hydra/job_logging: custom
        - _self_

train:
        batch_size: 16
        perc_valid: 0.1

hydra:
  run:
    dir: ../hydra/${hydra.job.name}/${now:%Y-%B-%d_%H-%M-%S}

